version: "3"
services:
  app:
    container_name: sinatra
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:4567"
    volumes:
      - .:/app
      - rubygems:/usr/local/bundle
    networks:
      - initiatives
    env_file:
      - .env
volumes:
  rubygems:

networks:
  initiatives:
    external: true
