source 'https://rubygems.org'

gem 'sinatra'
gem 'rackup'
gem 'puma'
gem 'omniauth-google-oauth2'
gem 'dotenv', require: 'dotenv/load'
gem 'bcrypt'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'sqlite3'
